### ISSUE TITLE
[Bug] related to literal.Builder in bolt.go

### ISSUE THREAD

**Issue by hnbeck** [xllora/bwdrivers#1]
In the function 

_func (d *driver) Graph(ctx context.Context, id string) (storage.Graph, error)_ 

a _graph_ struct is returned at end. But the field _lb_ is not set, therefore it is nil in the returned graph struct. This causes 0 pointer errors for example on query for a literal object.

It should be
return &graph{
        id: id,
        db: d.db,
                **lb: d.lb // missing part**
    }, nil

same holds for the function _NewGraph_

**Comment by hnbeck** [comment]
Thanks for reacting on this :)  To inform you what I do with Badwolf : I'm working on some kind of web game engine, handling rules in PROLOG and storing rules and facts via Badwolf  on disk. That's the plan ;) RDF tripples seem interesting for me for this task,

**Comment by xllora** [comment]
That sounds fun. Feel free to file any issues you may run into :)
