### ISSUE TITLE
updated bw tool run with subcommands ignores commandline driver flag values

### ISSUE THREAD

**Issue by ginseam** [xllora/bwdrivers#3]
It appears that the updated bw tool does not correctly parse or pass the arguments/flags for the bolt database(and perhaps other drivers) when invoked with a subcommand(ie 'bql','server',...). The default values are used regardless, with the result that the BWBOLT driver and associated configuration options are inaccessible via the commandline. 

I added two printfs for *boltDBPath and *driverName beneath the flag.Parse() in main() to demonstrate the flag/variable values. Adding '=' between flag and value can alter parsing behavior, but does not have any effect on driver flag values.    

If the defaults are modified in the source code, for example with driverName to 'BOLT' and boltDBPath to 'bar.db' the bolt driver and database appear to work and persist correctly with the subcommands.  

examples:

no subcommand, correctly parsing values,'foo.db' is created if it does not exist, 'foo.db' seems to be also parsed as a command
```
$ ./bw -bolt_db_path foo.db -driver BWBOLT
boltDBPath: foo.db
driverName: BWBOLT
command "foo.db" not recognized. Usage:
...
```

with '=', missing command correctly identified
```
./bw -bolt_db_path=foo.db -driver=BWBOLT
boltDBPath: foo.db
driverName: BWBOLT
missing command. Usage:
...
```

subcommand 'bql', incorrectly using default values  
```
$ ./bw bql -bolt_db_path foo.db -driver BWBOLT
boltDBPath: 
driverName: VOLATILE
Welcome to BadWolf vCli (0.8.1-dev)
Using driver "VOLATILE". Type quit; to exit
Session started at 2017-08-30 12:14:50.032730347 +0000 UTC m=+0.011496867
...
```

subcommand 'server', incorrectly using default values, port incorrectly parsed  
```
$ ./bw server 8080 -bolt_db_path foo.db -driver BWBOLT
boltDBPath: 
driverName: VOLATILE
2017/08/30 12:15:22 [2017-08-30 12:15:22.883815494 +0000 UTC m=+0.006301636] Invalid port number "BWBOLT"; strconv.Atoi: parsing "BWBOLT": invalid syntax
...
```

subcommand 'server', incorrectly using default values, port correctly parsed but positionally ambiguous
```
$ ./bw server -bolt_db_path foo.db -driver BWBOLT 8080
boltDBPath: 
driverName: VOLATILE
2017/08/30 12:16:04 [2017-08-30 12:16:04.878077288 +0000 UTC m=+0.006620474] Starting server at port 8080
...
```

**Comment by xllora** [comment]
Thanks for the report. I will take a look soon.

**Comment by xllora** [comment]
Mmh, this  seems to be the result of how the Go flag library works together with the CLI. It assumes the flags are the first thing you pass before you select any command. The fix may require also some fixing on the original code for command dispatching. Will dig a bit more tomorrow.

**Comment by xllora** [comment]
https://github.com/google/badwolf/commit/1495d07013b3ce7ff6abfea27586399674012af5

I updated some of the command processing to use the default args extracted by the flag package. One thing to keep in mind is the flags are global (it does not use FlagSets), hence the flags are expected between the `bw` and its commands. That means your examples 3, 4, and 5 will not work since the flag package will consider them as arguments.

**Comment by ginseam** [comment]
Thanks for the changes and explanation. Driver flag tests were successful with the 'bql' and 'server' commands. I used the term 'subcommand' in my initial issue, but here have substituted 'command' as you have used in your comments.

From your informative comments, this is my understanding of the correct way to use ```bw``` with flags and a command:
```
bw  <flag(s)>  <command>  <command argument(s)>
```

Would it be possible to update the ```bw``` usage message to reflect the necessary order? Or add a note/example on flag position? I would be happy to open another issue(perhaps 'bw cli help behavior')  to discuss this and other cli messages if it is useful.

For others who may read this, the correctly running versions of my examples 3,4,5 are:
```
$ ./bw -driver BWBOLT -bolt_db_path foo.db bql
```
```
$ ./bw -driver BWBOLT -bolt_db_path foo.db server 8080
```

**Comment by xllora** [comment]
https://github.com/google/badwolf/blob/master/docs/command_line_tool.md#usage

Mentioned that flags should appear before he command you want to run. I have reworded it a bit and also ugdated the driver README. Please see:

https://github.com/google/badwolf/commit/c6e955b7b1f0274cce5e508681d2c2a77fb6f876
https://github.com/xllora/bwdrivers/commit/4743aee734536fe1a3fafb66b12f5a1034ea5d3a
